In [21]:
import baselines as b
import simulations as s
import numpy as np

In [22]:
N = 10  # Num students
Q = 5  # Num questions
C = 2  # Num concepts
guess_prob = 0.25
student_matrix, questions_matrix = s.generate_matrices(N, Q, C)

In [23]:
student_matrix

array([[0.44958844, 0.11814064],
       [0.86746022, 0.62648255],
       [0.15642549, 0.75208579],
       [0.27324873, 0.91933304],
       [0.61605849, 0.22230653],
       [0.63032451, 0.31845674],
       [0.93226324, 0.76768342],
       [0.19920497, 0.58473246],
       [0.67647232, 0.40025556],
       [0.76161301, 0.42288631]])

In [24]:
questions_matrix

array([[0.15931168, 0.        ],
       [0.        , 0.77286573],
       [0.        , 0.79744536],
       [0.49645632, 0.        ],
       [0.82066732, 0.        ]])

In [27]:
fake_data = np.zeros((student_matrix.shape[0], questions_matrix.shape[0]))
for i, student in enumerate(student_matrix):
    for j, question in enumerate(questions_matrix):
        concept = np.nonzero(question)[0]
        prob = b.sigmoid_irf(student[concept], guess_prob, question[concept])
        if np.random.uniform() <= prob:
            fake_data[i, j] = 1
fake_data

array([[1., 0., 0., 1., 1.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 0., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 0., 0., 1., 0.],
       [1., 0., 1., 1., 1.]])