In [34]:
import baselines as b
import simulations as s
import numpy as np

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [35]:
N = 10  # Num students
Q = 5  # Num questions
C = 5  # Num concepts
guess_prob = 0.25  # Guessing threshold for student
l = 10 # lambda for floored exponential. Note that we are fixing it at a constant, need to figure out what value to use. 

# Pipeline

## Uncorrelated Student Abilities

Uncorrelated: Student abilities are sampled from independent normal distributions. 

In [36]:
student_matrix, questions_matrix = s.generate_matrices(N, Q, C)

In [37]:
student_matrix

array([[0.9228216 , 0.71908405, 0.88430657, 0.75352895, 0.55236638],
       [0.23031986, 0.325379  , 0.46023039, 0.91849283, 0.36458489],
       [0.84056474, 0.04895415, 0.74951552, 0.31066802, 0.36448525],
       [0.37766776, 0.50744627, 0.58110187, 0.78549121, 0.6023594 ],
       [0.34823317, 0.50200407, 0.78724569, 0.41897184, 0.60377801],
       [0.40037831, 0.08726337, 0.6887737 , 0.53408108, 0.4830659 ],
       [0.44698911, 0.84557169, 0.79176456, 0.20772081, 0.44424366],
       [0.56457249, 0.63684089, 0.25232947, 0.49175967, 0.31943554],
       [0.81175205, 0.91449856, 0.80364538, 0.11034651, 0.2744497 ],
       [0.4365156 , 0.07457959, 0.84187191, 0.54894643, 0.43910644]])

In [38]:
questions_matrix

array([[0.4716003 , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.42795482],
       [0.62948442, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.35044917, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.90404273, 0.        ]])

#### Generate with Sigmoid IRF

In [39]:
s.generate_responses(student_matrix, questions_matrix, guess_prob, b.sigmoid_irf)

array([[1., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 1., 1.],
       [0., 1., 1., 1., 0.],
       [0., 0., 1., 0., 0.],
       [1., 1., 0., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.]])

#### Generate with Floored Exponential

In [40]:
s.generate_responses(student_matrix, questions_matrix, guess_prob, b.floored_exp_irf, l)

array([[1., 1., 1., 1., 0.],
       [0., 0., 0., 1., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 0., 1., 1., 0.],
       [1., 0., 1., 0., 0.]])

## Correlated

Student abilities are sampled from a normal distribution with mean theta, where theta is sampled from a normal distribution.

In [41]:
student_matrix, questions_matrix = s.generate_matrices(N, Q, C, correl=True)

In [42]:
student_matrix

array([[0.26511797, 0.20658636, 0.64600288, 0.54256674, 0.91585937],
       [0.49294039, 0.55598455, 0.48820622, 0.30893293, 0.98017028],
       [0.54427657, 0.97849749, 0.33520979, 0.65224855, 0.59654044],
       [0.64531017, 0.7680205 , 0.39079632, 0.2241699 , 0.9245442 ],
       [0.57749998, 0.10696597, 0.79918848, 0.90927121, 0.08324387],
       [0.32420095, 0.41190952, 0.79958283, 0.58423377, 0.58068892],
       [0.54185414, 0.15676565, 0.29101328, 0.26416403, 0.66156933],
       [0.18971624, 0.30252612, 0.53112968, 0.64174687, 0.56426249],
       [0.45822753, 0.1551195 , 0.35629883, 0.78441563, 0.66054253],
       [0.59115062, 0.6263604 , 0.39635237, 0.2686601 , 0.55158569]])

In [43]:
questions_matrix

array([[0.34338594, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.33215206, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.48350246],
       [0.        , 0.        , 0.        , 0.        , 0.89690335],
       [0.        , 0.        , 0.        , 0.40825277, 0.        ]])

#### Generate with Sigmoid IRF

In [44]:
s.generate_responses(student_matrix, questions_matrix, guess_prob, b.sigmoid_irf)

array([[1., 0., 1., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 0., 1., 1.],
       [0., 1., 1., 1., 0.],
       [1., 0., 1., 0., 0.],
       [1., 1., 1., 0., 1.],
       [1., 1., 0., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1.]])

#### Generate with Floored Exponential

In [45]:
s.generate_responses(student_matrix, questions_matrix, guess_prob, b.floored_exp_irf, l)

array([[0., 1., 1., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 0.],
       [1., 1., 0., 0., 1.],
       [0., 1., 1., 1., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 1.],
       [0., 1., 1., 0., 1.],
       [1., 0., 1., 0., 0.]])