In [40]:
import baselines as b
import simulations as s
import numpy as np

In [41]:
N = 10  # Num students
Q = 5  # Num questions
C = 2  # Num concepts
guess_prob = 0.25
student_matrix, questions_matrix = s.generate_matrices(N, Q, C)

In [42]:
student_matrix

array([[0.73089878, 0.64202144],
       [0.46874724, 0.29990117],
       [0.38390179, 0.64562539],
       [0.39821861, 0.85656146],
       [0.83336048, 0.49633372],
       [0.25533857, 0.3050716 ],
       [0.4762331 , 0.88310554],
       [0.8077714 , 0.40012254],
       [0.15430578, 0.37342873],
       [0.85535606, 0.75434821]])

In [43]:
questions_matrix

array([[0.        , 0.71780604],
       [0.4560526 , 0.        ],
       [0.        , 0.61576407],
       [0.        , 0.58352718],
       [0.20550357, 0.        ]])

In [44]:
# Generate simulated data: N x Q matrix where m_ij = 0 iff student i responded question j correctly.
fake_data = np.zeros((student_matrix.shape[0], questions_matrix.shape[0]))
for i, student in enumerate(student_matrix):
    for j, question in enumerate(questions_matrix):
        concept = np.nonzero(question)[0]
        prob = b.sigmoid_irf(student[concept], guess_prob, question[concept])
        if np.random.uniform() <= prob:
            fake_data[i, j] = 1

In [45]:
fake_data

array([[1., 1., 0., 0., 1.],
       [1., 1., 0., 0., 1.],
       [0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 1., 0., 1.],
       [1., 1., 1., 0., 0.],
       [0., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1.]])