In [5]:
import baselines as b
import simulations as s
import numpy as np

# Pipeline

We will run the full pipepile with "uncorrelated" and "correlated" student generated data. Uncorrelated data means that student skills are independent from each other, and "correlated" means that they are generated using a latent variable. 

## Uncorrelated

In [6]:
N = 10  # Num students
Q = 5  # Num questions
C = 2  # Num concepts
guess_prob = 0.25
student_matrix, questions_matrix = s.generate_matrices(N, Q, C)

In [7]:
student_matrix

array([[0.58397649, 0.46787353],
       [0.26728575, 0.19892067],
       [0.56573923, 0.6752744 ],
       [0.54109582, 0.65455229],
       [0.64779568, 0.64211948],
       [0.17641549, 0.697126  ],
       [0.30700409, 0.52809754],
       [0.70224199, 0.58435885],
       [0.65999653, 0.40235561],
       [0.11326836, 0.44201139]])

In [8]:
questions_matrix

array([[0.53962436, 0.        ],
       [0.        , 0.53014124],
       [0.40966316, 0.        ],
       [0.        , 0.17398181],
       [0.        , 0.79699264]])

In [9]:
fake_data = np.zeros((student_matrix.shape[0], questions_matrix.shape[0]))
for i, student in enumerate(student_matrix):
    for j, question in enumerate(questions_matrix):
        concept = np.nonzero(question)[0]
        prob = b.sigmoid_irf(student[concept], guess_prob, question[concept])
        if np.random.uniform() <= prob:
            fake_data[i, j] = 1
fake_data

array([[1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [1., 0., 1., 1., 0.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 1., 0., 1.]])